### ISSUE TITLE
New Character button not working.

### ISSUE THREAD

**Issue by vedantsingh1404** [govindbalaji-s/random-character#1]
The colour of all 4 buttons changes when the New Character button is clicked. Nothing happens though.

<img width="1036" alt="Screenshot 2019-07-07 at 8 19 50 PM" src="https://user-images.githubusercontent.com/26629490/60770073-c50def80-a0f4-11e9-8994-cfba050a5128.png">

**Comment by vedantsingh1404** [comment]
@govindbalaji-s This error is occurring because the name API is not working. You can fix it by simply changing the API you use for getting random nicknames.

**Comment by govindbalaji-s** [comment]
@vedantsingh1404 Sorry, had missed the email when you opened the issue. I also just noticed that the API at https://randomnick.cdt.one/ is not working. Thanks for pointing out.
